#服务配置
server:
  #端口号
  port: 8090
  #Session超时时间
  session:
    timeout: 300

#数据源设置
spring:
  datasource:
    #数据库连接
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://49.4.69.128:1433;DatabaseName=demo
    username: sa
    password: kmxy@128
    #连接池配置
    initialSize: 5
    maxActive: 50
    minIdle: 5
  #redis设置
  redis:
    host: 127.0.0.1
    database: 1
    port: 6379
    password: xycom
    jedis:
      max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
      max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-idle: 8 # 连接池中的最大空闲连接
      min-idle: 0 # 连接池中的最小空闲连接
      timeout: 3000ms # 连接超时时间（毫秒）



logging:
  config: classpath:logback.xml
  level:
    com:
        dao: trace


mybatis-plus:
  mapper-locations: classpath:mapping/*.xml
